Add db schema
severynchuk/sql-cheatsheet pull request #1
Opened 2022-06-05 18:16 UTC by severynchuk

2022-06-05 18:20 UTC, ksen0byte reviewed
please squash your commits

2022-06-05 18:34 UTC, ksen0byte requested changes

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +![Database Schema](/images/database_schema.jpg)
1. make sure the image is optimized for web (proper size is set)
2. Let's make the background transparent
3. Crop the image

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| type_transactions | varchar   | not null   | purchase/sale    |
```suggestion
| transaction_type | varchar   | not null   | purchase/sale    |
```
This is an enumeration. The data type should be set appropriately.

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| column            | data_type | constraint | description      |
```suggestion
| Column            | Data Type | Constraint | Description      |
```

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| id_kontragenta    | integer   | not null   | kontragent id    |
id_kontragenta is grammatically incorrect

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| id_stock          | integer   | not null   | stock id         |
it should be `stock_id` instead of `id_stock`.
Do this for all the similar columns.

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| id_produkt        | integer   | not null   | produkt id       |
It's `product`, not produ**k**t

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| product quantity  | varchar   | not null   | product quantity |
```suggestion
| product_quantity  | varchar   | not null   | product quantity |
```
Column names should not contain spaces.

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| id     | integer   | not null   | kontragent's id    |
let's make it `kontragent ID`

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| product price     | varchar   | not null   | product price    |
It's a bad practice to store numbers in strings

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| od_vymir  | integer   | not null   | unit of measure for the quantity of goods |
od_vymir  is not an english word

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| pereriz   | varchar   | not null   | wire cross-sectional area  |
same here

2022-06-05 18:34 UTC, ksen0byte commented on README.md
> +| id     | integer   | not null   | stock id     |
find out how to autoformat tables in vscode

make sure they look pretty, so that the number of spaces is equal in every line

2022-06-05 19:23 UTC, severynchuk commented on README.md
> +![Database Schema](/images/database_schema.jpg)
I couldn't make the background transparent, but I cropped the image.

2022-06-06 16:18 UTC, ksen0byte requested changes

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +| product_id        | integer   | not null   | produkt ID       |
```suggestion
| product_id        | integer   | not null   | product ID       |
```

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +### stock
```suggestion
### stocks
```

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +| contractor_id     | integer   | not null   | contractor ID    |
it's incorrect on the picture

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +| product_id        | integer   | not null   | produkt ID       |
by the way, it is incorrect on the picture

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +| product_quantity  | numeric   | not null   | product quantity |
In the pic, it is `double`. Let's align.

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +| id     | integer   | not null   | contractor's ID    |
```suggestion
| id     | integer   | not null   | contractor ID    |
```

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +| phone  | integer   | not null   | contractor's phone |
I doubt we should set the phone to `integer`. What if it will be `+380...`?
I suggest setting the appropriate data type for this column.

2022-06-06 16:18 UTC, ksen0byte commented on README.md
> +| cross_section | varchar   | not null   | wire cross-sectional area                 |
double-check that all the properties listed here are aligned to the picture and vice versa

2022-06-14 18:19 UTC, ksen0byte requested changes

2022-06-14 18:19 UTC, ksen0byte commented on README.md
> +| id                | integer   | not null   | transaction ID   |
please, specify in `Constraint` if the field has a foreign or primary key constraint

2022-06-14 18:19 UTC, ksen0byte commented on README.md
> +| id     | integer   | not null   | manufacturers ID     |
```suggestion
| id     | integer   | not null   | manufacturer ID     |
```

2022-06-14 19:05 UTC, ksen0byte approved these changes

2022-06-14 19:12 UTC, merged